### PR TITLE
fixes issue #62 invalid input Isac

### LINKED ISSUE #62: Add invalid test cases in functions and test - ISAC

### PR DESCRIPTION
**Pull request by isacarvid**
* adds invalid input testing for lic6
* adds invalid input testing for lic10
* adds invalid input testing for lic2

### CODE REVIEW

**Review by evkade — APPROVED** [review]

File: lab1/src/main/java/lab1/Decide.java [hunk 1]
```diff
@@ -229,6 +233,9 @@ boolean LIC5() {
 	 * at:(https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line)
 	 */
 	boolean LIC6() {
+		if(3 > parameters.nPts || parameters.nPts > numpoints || parameters.dist < 0) {
```
Comment (ayubatif) [inline lab1/src/main/java/lab1/Decide.java:236]: this should be `3 < parameters.nPts`

**Review by ayubatif — COMMENTED** [review]
Fix the input validation in LIC6
